import 'package:flutter/material.dart';

const Color primary = Color.fromARGB(0xFF, 0x3D, 0x3D, 0x8E);
const Color white = Colors.white;
const Color blue = Colors.blue;
const Color sb1 = Colors.blueAccent;
const Color sb2 = Colors.pink;
const Color sb3 = Colors.cyanAccent;
const Color grey = Colors.grey;
const Color green = Colors.green;
const Color deepPurple = Colors.deepPurple;
const Color yellow = Colors.amber;
const Color black = Colors.black;
const Color red = Colors.red;
const Color transparent = Colors.transparent;
const Color bluesgrey = Colors.blueGrey;
const Color newcolor = Color(0xFFE7E8FE);
const Color homescreencolor = Color.fromARGB(255, 142, 177, 235);
const Color favcolor = Color.fromARGB(255, 244, 128, 118);
const Color searchcolor = Color.fromARGB(217, 224, 228, 4);
const Color profilecolor = Color.fromARGB(255, 255, 225, 0);
const Color goaltilecolor = Color(0xFFE7E8FE);
